import { getProductsInCollection } from "../lib/shopify"

import Head from 'next/head'
import Hero from '../components/Hero'
import ProductList from '../components/ProductList'

export default function Home({products}) {

  return (
    <div>
      <Hero/>
      <div className="container mx-auto">
        <Head>
          <title>Quill Stationary - Shopify NextJs Tailwind demo</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <ProductList products={products} />
      </div>
    </div>
  )
}

export async function getStaticProps() {
  const products = await getProductsInCollection()
  const stickyHeader = true

  return {
    props: { products, stickyHeader }
  }
}